POST http://localhost:58774/orders
Content-Type: application/json

{
  "items": [
    {
      "quantity": 10,
      "description": "Coca-cola"
    },
    {
      "quantity": 5,
      "description": "Mc Chicken"
    }
  ]
}


###

GET http://localhost:8082/orders-ms